name: WFM Slack Bot
on:
  schedule:
    - cron: '45 * * * *'  # <-- Ahora se activará a las y 45 de cada hora
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerias
        run: |
          pip install pandas gspread google-auth requests pytz

      - name: Ejecutar Bot de WFM
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python bot.py
